---
- hosts: shell_runners
  become: true
  gather_facts: true
  vars_files:
    - vars/main_shell.yaml
    - ./secrets.yaml
  roles:
    - role: gitlab-runner
  tasks:
    - name: Install mysql client
      apt:
        update_cache: yes
        pkg:
          - mysql-client
